version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00" # UTC
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "pytest"
        versions: [">=9"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30" # UTC
    labels:
      - "dependencies"
      - "actions"
    open-pull-requests-limit: 5
