name: CI

on:
  push:
    branches: [ main, master, revert-pre-2025-09-16 ]
  pull_request:
    branches: [ main, master, revert-pre-2025-09-16 ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy safety

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy --exclude 'tests/' --ignore-missing-imports . || true

      - name: Security audit (safety)
        run: |
          safety check || true

      - name: Run tests
        run: |
          pytest -q || pytest -q -k "not perf"

      - name: Upload coverage artifact (optional placeholder)
        if: always()
        run: |
          echo "Add coverage.xml generation later"
