name: Config Governance

on:
  pull_request:
    paths:
      - 'docs/config_dict.md'
      - 'tests/test_config_doc_coverage.py'
      - 'tests/config_doc_baseline.txt'
      - 'config/**'
      - 'src/**'
  push:
    branches: [ main ]

jobs:
  config-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run config doc coverage (strict)
        env:
          G6_CONFIG_DOC_STRICT: '1'
        run: |
          pytest -q tests/test_config_doc_coverage.py::test_all_config_keys_are_documented
