name: Logging-only try checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run logging-only try checker (warn mode)
        continue-on-error: true
        run: |
          python scripts/check_logging_only_try.py || exit 0
