name: Parity & Fatal Ratio Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt || true
      - name: Run parity/fatal gate
        env:
          PARITY_MIN: '0.985'
          FATAL_MAX: '0.05'
        run: |
          python scripts/parity_fatal_gate.py --parity-min ${PARITY_MIN} --fatal-max ${FATAL_MAX}
