name: sbom

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install (runtime + sbom extra)
        run: |
          python -m pip install --upgrade pip
          pip install .[sbom]

      - name: Determine version
        id: ver
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
          fi

      - name: Generate SBOM
        run: |
            python scripts/gen_sbom.py --output sbom_${{ steps.ver.outputs.version }}.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.ver.outputs.version }}
          path: sbom_${{ steps.ver.outputs.version }}.json

      - name: Attach to release (tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.version }}
          files: sbom_${{ steps.ver.outputs.version }}.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
